#nacos:
#  config:
#    server-addr: 127.0.0.1:8848    ##用nacos做配置中心动态修改配置参数,如果配置中心挂了则用项目里的配置文件
#    #server-addr: 192.168.127.131:8848  #nginx的配置url （集群时是VIP地址）
server:
   port: 8087
city: zhanjian
# mysql springBoot2.0之后的话是com.mysql.cj.jdbc.Driver
spring:
  application:
    name: member-service
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///zjs?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password:
  redis:
      host: 192.168.127.130
      port: 6379
      timeout: 3000

#  data:
#    mongodb:
#      host: 192.168.106.128
#      port: 27017
#  elasticsearch:
#    rest:
#      uris: 192.168.106.128:9200   ##注意这是ES7.x的配置方式, 对应springboot版本必须是2.2.x才兼容
#      uris: 192.168.106.128:9200,192.168.106.128:9202,192.168.106.128:9203

  rabbitmq:
    host: 192.168.106.128
    username: guest
    password: guest
    port: 5672
    publisher-confirm-type: correlated        #消息投递到到交换器Exchange后触发回调
    publisher-returns:  true                  #消息投递从交换器发送到对应queue失败时触发回调
    #template:
      #mandatory: true                        #开启接收消息投递 无法路由的 回调开总开关默认是true
    listener:
      simple:                                 #点对点方式
        acknowledge-mode: manual              #消费手动ack  -- simple是点对点方式/topic也属于点对点
        retry:
          enabled: true                       #开启消费重发-- 默认不重发
          max-attempts: 5                     #最大次数
          max-interval: 3000                  #重试间隔5000ms
          initial-interval: 2000              #第一次和第二次之间的重试间隔
      direct:                                 #发布/订阅方式
        acknowledge-mode: manual              #手动ack     --  direct是发布/订阅方式

        #retry:
          #enabled: true                      #direct方式的retry配置是不生效的 全部是走simple的方式配置
          #max-attempts: 3
          #max-interval: 5000


####阿里支付配置
alipay:
  app_id: 2016102000727283
  merchant_private_key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCQKZeWbwlQVfMEJsJNlF1SLpHlb9m/kBo3wIIqaK24+69tanh6EvMQIIJWjz/lpB/yd2uk2F67cn7gGYB7dvdKxu7g3/8JmkKs9GM/BtrvtFhrxHwytjiTNPZJjs8fWcX3zzif+dXdKiFT6zPLt+PV0S81ZdVfCUqXrFO1AFC7gvf/cRXsq53PGy5C+CvsbnFmn05bUwldwoFoDL2oSA3x710KzpNFi0XWR/Wf8KdiucNXbgq9Q+Y/1WOCRFAhwe8kFFnaNS8QKamnHi8bVJRiqD2eCbrfPty9z0/VjW93RasC2fisYz/qKSue8cYyvaZ/wtiqfB+vjnbiDrOdm9pjAgMBAAECggEAZeCeubbaVCWJSYPCiGSy1mMGw6eZsCC8Bm5LDoFPU4y52o8FeO9vShRPR7CQLU8hLI5sSeCGgd1WADTFcXsPI48WPWDOsRCM0gEbKe1ER2WhnvcJ9iSEMrOY4T7E7JjaqFeO4q8CDfu59b4fqnXX0sCzpf7DHRhJ2In11dHVO80tb7azcxR1G/ZqB4OMF6RfX26+6YWLiCscT9oxx1w0WjlXDdEzjv9oB/cOcV0ZTnVf+0p2Mddru3nTOqISIdzJak0lJyDna0XTKbt8u62PmaKbIIYUL4P9PyPIMTAk+xXE+QBL59QMRXZvER0Eob9SoApUkxvc64gniSpYFY8HsQKBgQDgnhea7Mnd98LiA4Z8NNbWGks5egkNrD0GQC5lpDCo3GLE7sDm9UBuT51T3YMSiEZYkvAsOVm+Yhsyfpdi8gkOcQIGuUi+mJxzfCGUSRj/RSjjz4FMUxQNIkD10CeyiyngVYCtHegJIlqCPAWEytXuoh6XLg0dIIE/CX+siniKdQKBgQCkTdveEHnSDrX6TDcFE7ubaOenCU4zSl0pMyzKvGOQsZSt6iZcv/m0KicK0tjjbGfoCe/Cp7OlYRtnrbzuDI/x9hsYJhjVQ+guOMpyHxXVb//k0Roh59hb2EOoKc+FptV+KVLEh8sV6rFfxhuM0ZRzOp6lxNG1aNQiqxnwAOnGdwKBgHQdZciB9g0YIpeiCOi2jATcTNzmmD2IN3e+v/1tNnZkj26Mmg4K5IbiA0uybCqtZegt9Zh3AUyo/LRKusm8oy/i/ZAqQk+9JsuQdO9qJlD4GJ5Dy+x/2hK8DWbFd3AV/szohn93wVbPeohurM+r55HYHwY6GS9geU/0AhtY7d1tAoGACzbJL+Hd/qlEYF39T1pmbpf9X5gx/ywvKZW1k+zBuulz5V7a2W+84kASRBnZ9cO7X8n11EpP55S2IyBnibPPy0rp1H8dKMkmuqjjoGBgxB2N0Jc4+mFxkeszyvF3mX6miaLWZFWEVe2bx5ak4LqZMDgrBdNmIMST3f3hmlDlo8cCgYALykRmdctAPhsBBUQLW/apb6lZ8Qob3fEvmtbV/5eWdCvgE53qqp8OUtBjid8U8D4bADE926t7lUrOVi1ywDgnmxLyJFQS2+FQCob+yxcZllDs3UKMvhxXjvuGKepUqcpcGahDXyG+sCEAoe5LPqTdkKGhkbbnhuYN4dtl8iqpiw==
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiEBNz32rvYxwANv1YewJUHGluB/O91TxArvFp/lcm7bsqoAF3MVbr4gHZ15ijKpbfHQJ9bdnGd3DW4sznh9BHOERAIkCR59scU7AvpOGTJQHFCK+3bX5/T4NOrpPyJbh0wmrXo7H4IvPkuTb0EEoVSqbEoG+CFLlFc1JkwvPbrFWftR9obXjrjgHepJyfye6jSD8Vw106QigqUWrpFncs3T33LM03ei42qUGesUlUA0UzWuUnT7GC8umXSZMD79oUejlZV7KgxU6G26YG21C4rKkMWaqlAIrevOkr9YJnbqD+n5xRegjWVPukVknqJI6AXmv8I2lmvCzh7zqihIdPQIDAQAB
  notify_url: http://z35i6z.natappfree.cc/pay/success
  return_url: http://www.baidu.com
  sign_type: RSA2
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
  charset: utf-8

###JWT 配置
gmall:
  jwt:
    secret: 2432sdsdAD@#@#sfdsf23 #盐
    pubKeyPath: D:\java-data\谷粒商城springCloud项目\rsa\rsa.pub #公钥存放地址  要在服务器上先建好D:\java-data\谷粒商城springCloud项目\rsa的目录
    priKeyPath: D:\java-data\谷粒商城springCloud项目\rsa\rsa.pri #私钥存放地址
    cookieName: gmall-cookie
    expire: 30 #过期时间 30mins


#####xxl-job配置
#xxl:
#  job:
#    admin:
#      addresses: http://localhost:8080/xxl-job-admin
#    executor:
#      ip:
#      port: 9998
#      logpath: /xxl-job-logs/
#      appname: xxl-job-demo
#    accessToken:

























#mybatis别名配置
#mybatis.type-aliases-package=member.center.com.pojo
#mybatis.mapper-locations=classpath:member.provider.mapper/*.xml
#mybatis-plus 配置
#mybatis-plus.mapper-locations=classpath*:**/mapper/*Mapper.xml
#默认驼峰转大写策略是true
mybatis-plus:
       configuration:
          map-underscore-to-camel-case: true
#主键类型 AUTO:“数据库ID自增”, INPUT:“用户输入ID”, ID_WORKER:“全局唯一ID (数字类型唯一ID)”, UUID:“全局唯一ID UUID”;
       global-config:
           db-config:
               id-type: AUTO
#mybatis-plus.global-config.db-config.id-type= UUID

#elastrisearch配置--6.x,5.x版本是这么配置  7.x就不是了
#spring.data.elasticsearch.cluster-name=elasticsearch
#spring.data.elasticsearch.cluster-nodes=127.0.0.1:9300
#集群节点 逗号隔开
#spring.data.elasticsearch.cluster-nodes=127.0.0.1:9300,127.0.0.1:9301,127.0.0.1:9302


#rabbitMq配置
#spring.rabbitmq.host=192.168.127.130
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest
#spring.rabbitmq.port=5672
# 开启发送确认
#spring.rabbitmq.publisher-confirms=true
# 开启发送失败退回
#spring.rabbitmq.publisher-returns=true
#开启接收不到路由的消息
#spring.rabbitmq.template.mandatory=true
#spring.rabbitmq.listener.direct.acknowledge-mode=manual
#spring.rabbitmq.listener.simple.acknowledge-mode=manual
#监听大小5个
#spring.rabbitmq.listener.simple.concurrency= 5
#最大10个监听
#spring.rabbitmq.listener.simple.max-concurrency= 10


###mongodb配置
#spring.data.mongodb.host=192.168.127.130
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=school


#redisConfig 配置
# Redis服务器地址
#redis.host=192.168.127.130
# Redis服务器连接端口
#redis.port=6379

# Redis服务器连接密码（默认为空）
# 连接超时时间（毫秒）
# 连接池最大连接数（使用负值表示没有限制）
#spring.redisConfig.pool.max-active=8
# 连接池最大阻塞等待时间（使用负值表示没有限制）
#spring.redisConfig.pool.max-wait=-1
# 连接池中的最大空闲连接
#spring.redisConfig.pool.max-idle=8
# 连接池中的最小空闲连接
#spring.redisConfig.pool.min-idle=5


